# Namespace for the frontend
namespace: frontend-ns

# Docker Image details
image:
  repository: nabilaebrahim/private-repo
  tag: frontend
  pullPolicy: Always 

# Replicas
replicaCount: 2

# Domain name for Ingress access
host: helm-storm.local

# Backend FQDN
backendUrl: "https://helm-storm.local/check-user"

backendNamespaceLabel: backend-ns

# Frontend Specific Configuration
frontend:
  hpa:
    minReplicas: 2
    maxReplicas: 5
    targetCPU: 50
    targetMemory: 70  