apiVersion: v1
kind: ResourceQuota
metadata:
  name: backend-quota
  namespace: {{ .Values.namespace }}
spec:
  hard:
    pods: {{ .Values.quota.pods | quote }}
    requests.cpu: {{ .Values.quota.requestsCpu | quote }}
    requests.memory: {{ .Values.quota.requestsMemory | quote }}
    limits.cpu: {{ .Values.quota.limitsCpu | quote }}
    limits.memory: {{ .Values.quota.limitsMemory | quote }} 