apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: {{ .Values.namespace }}
spec:
  encryptedData:
    .dockerconfigjson: AgA4ykB2PYV34mrAxnlpZRdsrWukBCFvi05V8EQlBmS/04qQdBACQkc+MEL46gY/jJ3ibIufDKCeIlXFI1k2a+yVh/lB1IOGKQFXNJWKmI15dYXdc2D5SWzOO/aafrEvGbLflqyws8Rt5KkxVoLnQP2zlZE/MEsWdk+gpnbM3sJengIIQlZaOf8Vexxn6wKMQRUT3VVS6uBTJMAVhH7O7BfvAC0nB9p/J40cx0rNJ8X/KVzMt3nYhpaIUZpxSbBYwOibnXkViBQ56sygsta891wmbPkhuU8CjCUgNUqARpqz09lQcfdBw20KMVo+pZEqLouDo7J0HKYQvIblHZY8v3oxDTmSrmqj6ozq9+hK/JoHpvRjk7dZquzjL9nh0cidDhOSY0AckMf5q7z+4g2MjXAsmG69J0KQsnUuM2kYqOAyqx6xAI25O7zkmubOAK5trchBxfXWY4DgcuNHzC5A0GpKFCbwVJMjxu4Vut0m/zECd3Z0E61iGmcvh8NqSwLuy8rcdD6kA7lmMx4YPzkD+Bx+R3pdEfyEo0naOlJBsOT8SY49VJ90PESWzFrdWUhMzNtKPjrFNWi/RDLowefxXd5gZNoqR5n980M7cKVUSNI5c4iWnTHtys6jRYcWlu7YnZQz5NOikz7Zv5FJ6kwtmXF4dnL2VXKzi91MJYKoiYeX8EddYJxCik/nEIVb4vKFZI1MVab1sjxDPpBFTTZRr66OrHKnELFvP+3sc6hQ+ZH3y1s86I7Z+JqbT45Rls6H9GouRTK0L1uqLQBiSzmUIf6O9VPAPmraN6ZG23J9x9CzDVCbmaXcUxHRkOOunxWFfoNFb7WWIHgpuuy4LQfc2W5mNZZE1oNq++hT2FNkgR368uvI6eOKkSODMIzcW65D5RnQxXBR34urLHcKVX/P1PXaE+zK5KchpThZ4eLOMGcGotIaEpZ+mhEKgtQEiukd44Ix8sPmA98kFfA=
  template:
    metadata:
      name: regcred
      namespace: {{ .Values.namespace }}
    type: kubernetes.io/dockerconfigjson