apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: backend-ns
spec:
  encryptedData:
    .dockerconfigjson: AgBvuSRF6ySIt6ztsvoFl5t5Yf6O5t0tH7B4d55Hh0D9vPJXqMTjk4b8YOP/vStIr124g2UcJntkmkPx2vZ4Yj9c9YxhNQOcUOVOl3ZTpc0dWHRA2lq3Dt/rzo0fWFxleMIWRJT/kq/JI6wNIIbobcoa6TE7TiTV3vw9k9iZAaV7mEVjVnckU5txGjbSniDZoVVQd6X9zmnFaUUpgQbyXvFliQ5sjkl5Ko18pLBvTwK07g72jFSblExdNImYiNgf7z4QZiBp1J35vNsHUPcK3znVIsK17Ve0lkSs8jeKK4qPs/VQyzkzZuxjvLmGCnvXx233+w7dkw8X2xripRu2PFKYku4G8RlxS4LCXS6vdAncNysccU8qKyYHP/11XtUCeMbMVyNDBPNmouhbjN83Qr5XLq6P4klgzDw9vs1EEceEk3lhEubVoXTh7/anmdCQlRJ4XNJi1pGsr2KqfNPbIPZmoDC2oiYrsqMBAi/IcfHbcfCdMGsqLpDCubh9wzhO4IR7zFLM09BIUKWDOgAw7p/2huX0l15Um7TdxxNrFIJqOXnyuCzgXd9we95diiyciY2Jnt7fDPihcYFsWSEmf/P1XqqkGw85OW6FWMoZNqoriUKkea2Ozi2GsfY7T86JvxYJt20AvlMkkTYHYM3NCg0swVFXzQri9/31VlugJvDSGJM+lAz841wp0aEFwI2CDoH7usSDiJsnFE+CFpXWMHgStEvqX+ZuXRpG1aPjSt3ybM8+3CyeAXOUXteO0qFNO/XcVTyfpFBMtBZMga+laxAXXnvD6yAQ/Iu4JL1XVPn/S/84guDBzMteypEZdKcHM1GCN2qagbmCndyhZtg8ravbblRd5n7PZMGokWPN8Do2NlGN/9k7kF9GEbW5mAN3dEiUQ+WyLBAEss1Y5qzf40dKNiaj94M8muSMBHMsWYmO7xfebycUIYtDh9+cKmlCpm2f
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: backend-ns
    type: kubernetes.io/dockerconfigjson

