apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: frontend-ns
spec:
  encryptedData:
    .dockerconfigjson: AgACdc5FXvULHmpaVgKf1n6yFGHAFS5G/pTk7c/qYLwm36nKU2xPw6K0+qMJGgMn3uYCQTyWBLBeUmnxemha6omjwUAstjYMNhf11n/tlY6OugotUP/Z069+m90Wyj9TDwZt3Dh6Tq9FXmtQyKE88VjP7NxPpNSaHcORvk2JEREMtR80mVGi4c375OrAFwNkrYx2f77PauP7OTZWPupSzskPrslbaLlTovV0xq/Gs3g4VgveWAGpO11ySPeqiYHrUPPdgMVvsLr64dqwcgmTGlAnWl5bjhOPWhhgpLe/LV5s4Muipt3/3mQBGB0Li7WlK6KQFCaa3zWPszV3x1q/RITq0Ysm6U4TAV1mgARduNi2xRPHpn6Py99eiAQ2lOh6sUuDzC7EY04aBqFxuCGehpBFLeuL/kPgL65WvzGt8EdBUg6qcehXhBh7A9AmRvFdyCO4dQu9S/A7+0WIo6EVzY/CIFXVvmROYLJtKz0vP5BTIX8YRFcpaqEXWJGb7Dr/vJ0LpZ9XcInNHAEQ7gBsKLnveAOHl18h8WdbwH2/hs6AM6vCF2/4eAYQgjWMaII2SCjZKQnoT2xNGs5s6KUtMmY0DlJWVlxhsNf+z39HgUCbCc+P/1hT9lcvynEPi064mMZsCN1L9Op5OJJAa8toHLdU4Ei9418UKEyAHxxR3gilD7p/0bZXm5CMY+RaoMCJyAKxMPsf+rsMCBHNoWKBmuVFFfWYA4tCd0ewgmvT9y+jFoh7xabiA1T07FnDQQv27+KcyVdzDZ102/sjN98lG+x0+I0AV97coosMb66Q9rC19XpMAffP7SS1C0mW1HkQdVFYryYgX0sBvd0VVb0r+n4QHZkjjmeIvtrTO28gXx2mJ21KjvZ2GiVdTaRrjkPod/x2xjp8cNS5ly1nm/JRS3NO4inEeLxr1DXUy7hnxGzd6/xSwa9II4ZiBhuVK9++xVhs
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: frontend-ns
    type: kubernetes.io/dockerconfigjson

