apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: frontend-ns
spec:
  encryptedData:
    .dockerconfigjson: AgAd1Vhwgi0r99bKvjiDThTZwWrTLFJozKIfx7J1RuICfgclC2I6pFo0RpJbvfsW41ijgM3ojtUuSGBrh/dzO+E+2j/4+d92vQoxHHndabRmQmE21pTLw/jgNP79Y+TwPoB+J+zFukJQexpHxEWqfzjTeXSjBHPFxj6ANAr8HTBEO/XipwdS6QzKeRRTNnskhj4uMVqOxZUt2TbQxnyfSw0tC8dUZ0NU/PApPigUKgtQq0Eh11eEQ81EfSyG2jQNP73Qux/L3cnVd0Qh+ZVobBsLck310cbRAY4Rls1vG0TGvV7/o1o+nbyODnaMvH/x7bg5KqVDaIsG54nTY/4ZmFy6Mm1C8YPFrB2Vvf5TY6/pG8Nm8sLTYQs2+ISxophhoROXgRBZKtF+cBwV/XrdyZzDKzY7joQSXsTmlLCzaEOjfc12g75mFPGShyfDUStH6gNEfSTPRQ9VNthZseq/Xk5xuc+06Mle1/XnQEUntL5spDMiBwP+r5RacFp4LzwT0n++ociaHFMjDlzrn/gc/++P58+qWTyANxpIOOoiZP/25PuOPfOXVxRbgn6NX8mXqmQg9hvf7i0IX8cmb82ooK4Baf6mp/YqU9pWZTgAFgDUzmKBeyknM8/yMVRa4W5SFyaKeuFau78XUwEjrYcEs1rgsgSpeibOuUmhLy/P36emISNqS4GqxwvCRgtHsWFX1lfDXijeIVJU2hfuVCb9v5yiyjJRTTQHzsjL+VQlfo2Q9ADKF3LDxY2sdUI0a4DdzHAcjl+ndyb5y9ps90lsg2qK01cORFveWB9HfDX2W1FpkH553uQ0fpvU39VtuL4ZZFVXU15ZRstx3f0ztn9J9NNZ7wGZ3I26SCHxMUS3rt+UdZacODEthEkQZB6jNWFHAlHWNs7mdCjXgh/4Rz24FtEP+lLxlY7y2elyMs5NmheHW6f1pTok8/PXKyUPqmGrUdOprq29ogwrPf0=
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: frontend-ns
    type: kubernetes.io/dockerconfigjson

