# apiVersion: v1
# kind: Secret
# metadata:
#   name: db-secret
#   namespace: {{ .Values.namespace }}
# type: Opaque
# data:
#   # Base64 for 'admin123'
#   postgres-password: YWRtaW4xMjM=

# apiVersion: v1
# kind: Secret
# metadata:
#   name: db-secret
#   namespace: {{ .Values.namespace }}
# type: Opaque
# data:
#   password: {{ .Values.dbPassword | toString | b64enc }}

apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  password: {{ .Values.dbPassword | toString | b64enc }}