apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClassName }}
# Use local-storage or provider specific provisioner
provisioner: k8s.io/minikube-hostpath 
volumeBindingMode: Immediate